# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Sampa Guide"
email: info@sampaguide.com
description: Um guia para explorar e “se perder” na cidade de São Paulo
baseurl: "/sampaguide" # the subpath of your site, e.g. /blog
url: "https://alfredmyers.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: sampaguide
github_username:  alfredmyers

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor

google_api_key: AIzaSyBLAgNaPxf28D8gsfcvuAqie4xrLrper2Y

collections:
  regioes:
    output: true
  bairros:
    output: true
    permalink: /regioes/:path/
  lugares:
    output: true
    permalink: /regioes/:path/

permalink: pretty

facebook_url: https://facebook.com/sampaguide
pinterest_url: https://www.pinterest.com/sampaguide/